/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as MaternelleRouteImport } from './routes/maternelle'
import { Route as LyceeRouteImport } from './routes/lycee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilleRouteImport } from './routes/famille'
import { Route as EnfantsRouteImport } from './routes/enfants'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as BlouseOfficielleRouteImport } from './routes/blouse-officielle'
import { Route as ApelRouteImport } from './routes/apel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CommandesRetourPaiementRouteImport } from './routes/commandes.retour-paiement'
import { Route as AideMentionsLegalesRouteImport } from './routes/aide.mentions-legales'
import { Route as AideLivraisonRouteImport } from './routes/aide.livraison'
import { Route as AideGuideTaillesRouteImport } from './routes/aide.guide-tailles'
import { Route as AideContactRouteImport } from './routes/aide.contact'
import { Route as AideConfidentialiteRouteImport } from './routes/aide.confidentialite'
import { Route as AideCgvRouteImport } from './routes/aide.cgv'
import { Route as AideCguRouteImport } from './routes/aide.cgu'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as EnfantsChildIdHistoriqueRouteImport } from './routes/enfants.$childId.historique'
import { Route as ApiPublicPayplugWebhookRouteImport } from './routes/api/public/payplug-webhook'
import { Route as ApiPublicEmailDiagRouteImport } from './routes/api/public/email-diag'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const MaternelleRoute = MaternelleRouteImport.update({
  id: '/maternelle',
  path: '/maternelle',
  getParentRoute: () => rootRouteImport,
} as any)
const LyceeRoute = LyceeRouteImport.update({
  id: '/lycee',
  path: '/lycee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilleRoute = FamilleRouteImport.update({
  id: '/famille',
  path: '/famille',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsRoute = EnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const BlouseOfficielleRoute = BlouseOfficielleRouteImport.update({
  id: '/blouse-officielle',
  path: '/blouse-officielle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApelRoute = ApelRouteImport.update({
  id: '/apel',
  path: '/apel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRetourPaiementRoute = CommandesRetourPaiementRouteImport.update({
  id: '/retour-paiement',
  path: '/retour-paiement',
  getParentRoute: () => CommandesRoute,
} as any)
const AideMentionsLegalesRoute = AideMentionsLegalesRouteImport.update({
  id: '/aide/mentions-legales',
  path: '/aide/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const AideLivraisonRoute = AideLivraisonRouteImport.update({
  id: '/aide/livraison',
  path: '/aide/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const AideGuideTaillesRoute = AideGuideTaillesRouteImport.update({
  id: '/aide/guide-tailles',
  path: '/aide/guide-tailles',
  getParentRoute: () => rootRouteImport,
} as any)
const AideContactRoute = AideContactRouteImport.update({
  id: '/aide/contact',
  path: '/aide/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AideConfidentialiteRoute = AideConfidentialiteRouteImport.update({
  id: '/aide/confidentialite',
  path: '/aide/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AideCgvRoute = AideCgvRouteImport.update({
  id: '/aide/cgv',
  path: '/aide/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AideCguRoute = AideCguRouteImport.update({
  id: '/aide/cgu',
  path: '/aide/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsChildIdHistoriqueRoute =
  EnfantsChildIdHistoriqueRouteImport.update({
    id: '/$childId/historique',
    path: '/$childId/historique',
    getParentRoute: () => EnfantsRoute,
  } as any)
const ApiPublicPayplugWebhookRoute = ApiPublicPayplugWebhookRouteImport.update({
  id: '/api/public/payplug-webhook',
  path: '/api/public/payplug-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailDiagRoute = ApiPublicEmailDiagRouteImport.update({
  id: '/api/public/email-diag',
  path: '/api/public/email-diag',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apel': typeof ApelRoute
  '/blouse-officielle': typeof BlouseOfficielleRoute
  '/boutique': typeof BoutiqueRoute
  '/college': typeof CollegeRoute
  '/commandes': typeof CommandesRouteWithChildren
  '/enfants': typeof EnfantsRouteWithChildren
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/cgv': typeof AideCgvRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
  '/commandes/retour-paiement': typeof CommandesRetourPaiementRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/email-diag': typeof ApiPublicEmailDiagRoute
  '/api/public/payplug-webhook': typeof ApiPublicPayplugWebhookRoute
  '/enfants/$childId/historique': typeof EnfantsChildIdHistoriqueRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apel': typeof ApelRoute
  '/blouse-officielle': typeof BlouseOfficielleRoute
  '/boutique': typeof BoutiqueRoute
  '/college': typeof CollegeRoute
  '/commandes': typeof CommandesRouteWithChildren
  '/enfants': typeof EnfantsRouteWithChildren
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/cgv': typeof AideCgvRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
  '/commandes/retour-paiement': typeof CommandesRetourPaiementRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/email-diag': typeof ApiPublicEmailDiagRoute
  '/api/public/payplug-webhook': typeof ApiPublicPayplugWebhookRoute
  '/enfants/$childId/historique': typeof EnfantsChildIdHistoriqueRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apel': typeof ApelRoute
  '/blouse-officielle': typeof BlouseOfficielleRoute
  '/boutique': typeof BoutiqueRoute
  '/college': typeof CollegeRoute
  '/commandes': typeof CommandesRouteWithChildren
  '/enfants': typeof EnfantsRouteWithChildren
  '/famille': typeof FamilleRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/cgv': typeof AideCgvRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
  '/commandes/retour-paiement': typeof CommandesRetourPaiementRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/email-diag': typeof ApiPublicEmailDiagRoute
  '/api/public/payplug-webhook': typeof ApiPublicPayplugWebhookRoute
  '/enfants/$childId/historique': typeof EnfantsChildIdHistoriqueRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apel'
    | '/blouse-officielle'
    | '/boutique'
    | '/college'
    | '/commandes'
    | '/enfants'
    | '/famille'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/aide/cgu'
    | '/aide/cgv'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
    | '/commandes/retour-paiement'
    | '/email/unsubscribe'
    | '/api/public/email-diag'
    | '/api/public/payplug-webhook'
    | '/enfants/$childId/historique'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apel'
    | '/blouse-officielle'
    | '/boutique'
    | '/college'
    | '/commandes'
    | '/enfants'
    | '/famille'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/aide/cgu'
    | '/aide/cgv'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
    | '/commandes/retour-paiement'
    | '/email/unsubscribe'
    | '/api/public/email-diag'
    | '/api/public/payplug-webhook'
    | '/enfants/$childId/historique'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apel'
    | '/blouse-officielle'
    | '/boutique'
    | '/college'
    | '/commandes'
    | '/enfants'
    | '/famille'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/aide/cgu'
    | '/aide/cgv'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
    | '/commandes/retour-paiement'
    | '/email/unsubscribe'
    | '/api/public/email-diag'
    | '/api/public/payplug-webhook'
    | '/enfants/$childId/historique'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApelRoute: typeof ApelRoute
  BlouseOfficielleRoute: typeof BlouseOfficielleRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CollegeRoute: typeof CollegeRoute
  CommandesRoute: typeof CommandesRouteWithChildren
  EnfantsRoute: typeof EnfantsRouteWithChildren
  FamilleRoute: typeof FamilleRoute
  LoginRoute: typeof LoginRoute
  LyceeRoute: typeof LyceeRoute
  MaternelleRoute: typeof MaternelleRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PanierRoute: typeof PanierRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AideCguRoute: typeof AideCguRoute
  AideCgvRoute: typeof AideCgvRoute
  AideConfidentialiteRoute: typeof AideConfidentialiteRoute
  AideContactRoute: typeof AideContactRoute
  AideGuideTaillesRoute: typeof AideGuideTaillesRoute
  AideLivraisonRoute: typeof AideLivraisonRoute
  AideMentionsLegalesRoute: typeof AideMentionsLegalesRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicEmailDiagRoute: typeof ApiPublicEmailDiagRoute
  ApiPublicPayplugWebhookRoute: typeof ApiPublicPayplugWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maternelle': {
      id: '/maternelle'
      path: '/maternelle'
      fullPath: '/maternelle'
      preLoaderRoute: typeof MaternelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lycee': {
      id: '/lycee'
      path: '/lycee'
      fullPath: '/lycee'
      preLoaderRoute: typeof LyceeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/famille': {
      id: '/famille'
      path: '/famille'
      fullPath: '/famille'
      preLoaderRoute: typeof FamilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants': {
      id: '/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof EnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blouse-officielle': {
      id: '/blouse-officielle'
      path: '/blouse-officielle'
      fullPath: '/blouse-officielle'
      preLoaderRoute: typeof BlouseOfficielleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apel': {
      id: '/apel'
      path: '/apel'
      fullPath: '/apel'
      preLoaderRoute: typeof ApelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes/retour-paiement': {
      id: '/commandes/retour-paiement'
      path: '/retour-paiement'
      fullPath: '/commandes/retour-paiement'
      preLoaderRoute: typeof CommandesRetourPaiementRouteImport
      parentRoute: typeof CommandesRoute
    }
    '/aide/mentions-legales': {
      id: '/aide/mentions-legales'
      path: '/aide/mentions-legales'
      fullPath: '/aide/mentions-legales'
      preLoaderRoute: typeof AideMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/livraison': {
      id: '/aide/livraison'
      path: '/aide/livraison'
      fullPath: '/aide/livraison'
      preLoaderRoute: typeof AideLivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/guide-tailles': {
      id: '/aide/guide-tailles'
      path: '/aide/guide-tailles'
      fullPath: '/aide/guide-tailles'
      preLoaderRoute: typeof AideGuideTaillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/contact': {
      id: '/aide/contact'
      path: '/aide/contact'
      fullPath: '/aide/contact'
      preLoaderRoute: typeof AideContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/confidentialite': {
      id: '/aide/confidentialite'
      path: '/aide/confidentialite'
      fullPath: '/aide/confidentialite'
      preLoaderRoute: typeof AideConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/cgv': {
      id: '/aide/cgv'
      path: '/aide/cgv'
      fullPath: '/aide/cgv'
      preLoaderRoute: typeof AideCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/cgu': {
      id: '/aide/cgu'
      path: '/aide/cgu'
      fullPath: '/aide/cgu'
      preLoaderRoute: typeof AideCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants/$childId/historique': {
      id: '/enfants/$childId/historique'
      path: '/$childId/historique'
      fullPath: '/enfants/$childId/historique'
      preLoaderRoute: typeof EnfantsChildIdHistoriqueRouteImport
      parentRoute: typeof EnfantsRoute
    }
    '/api/public/payplug-webhook': {
      id: '/api/public/payplug-webhook'
      path: '/api/public/payplug-webhook'
      fullPath: '/api/public/payplug-webhook'
      preLoaderRoute: typeof ApiPublicPayplugWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-diag': {
      id: '/api/public/email-diag'
      path: '/api/public/email-diag'
      fullPath: '/api/public/email-diag'
      preLoaderRoute: typeof ApiPublicEmailDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommandesRouteChildren {
  CommandesRetourPaiementRoute: typeof CommandesRetourPaiementRoute
}

const CommandesRouteChildren: CommandesRouteChildren = {
  CommandesRetourPaiementRoute: CommandesRetourPaiementRoute,
}

const CommandesRouteWithChildren = CommandesRoute._addFileChildren(
  CommandesRouteChildren,
)

interface EnfantsRouteChildren {
  EnfantsChildIdHistoriqueRoute: typeof EnfantsChildIdHistoriqueRoute
}

const EnfantsRouteChildren: EnfantsRouteChildren = {
  EnfantsChildIdHistoriqueRoute: EnfantsChildIdHistoriqueRoute,
}

const EnfantsRouteWithChildren =
  EnfantsRoute._addFileChildren(EnfantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApelRoute: ApelRoute,
  BlouseOfficielleRoute: BlouseOfficielleRoute,
  BoutiqueRoute: BoutiqueRoute,
  CollegeRoute: CollegeRoute,
  CommandesRoute: CommandesRouteWithChildren,
  EnfantsRoute: EnfantsRouteWithChildren,
  FamilleRoute: FamilleRoute,
  LoginRoute: LoginRoute,
  LyceeRoute: LyceeRoute,
  MaternelleRoute: MaternelleRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PanierRoute: PanierRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AideCguRoute: AideCguRoute,
  AideCgvRoute: AideCgvRoute,
  AideConfidentialiteRoute: AideConfidentialiteRoute,
  AideContactRoute: AideContactRoute,
  AideGuideTaillesRoute: AideGuideTaillesRoute,
  AideLivraisonRoute: AideLivraisonRoute,
  AideMentionsLegalesRoute: AideMentionsLegalesRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicEmailDiagRoute: ApiPublicEmailDiagRoute,
  ApiPublicPayplugWebhookRoute: ApiPublicPayplugWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
