/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as NiveauRouteImport } from './routes/niveau'
import { Route as MaternelleRouteImport } from './routes/maternelle'
import { Route as LyceeRouteImport } from './routes/lycee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnfantsRouteImport } from './routes/enfants'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as BlouseOfficielleRouteImport } from './routes/blouse-officielle'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AideMentionsLegalesRouteImport } from './routes/aide.mentions-legales'
import { Route as AideLivraisonRouteImport } from './routes/aide.livraison'
import { Route as AideGuideTaillesRouteImport } from './routes/aide.guide-tailles'
import { Route as AideContactRouteImport } from './routes/aide.contact'
import { Route as AideConfidentialiteRouteImport } from './routes/aide.confidentialite'
import { Route as AideCguRouteImport } from './routes/aide.cgu'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const NiveauRoute = NiveauRouteImport.update({
  id: '/niveau',
  path: '/niveau',
  getParentRoute: () => rootRouteImport,
} as any)
const MaternelleRoute = MaternelleRouteImport.update({
  id: '/maternelle',
  path: '/maternelle',
  getParentRoute: () => rootRouteImport,
} as any)
const LyceeRoute = LyceeRouteImport.update({
  id: '/lycee',
  path: '/lycee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsRoute = EnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const BlouseOfficielleRoute = BlouseOfficielleRouteImport.update({
  id: '/blouse-officielle',
  path: '/blouse-officielle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AideMentionsLegalesRoute = AideMentionsLegalesRouteImport.update({
  id: '/aide/mentions-legales',
  path: '/aide/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const AideLivraisonRoute = AideLivraisonRouteImport.update({
  id: '/aide/livraison',
  path: '/aide/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const AideGuideTaillesRoute = AideGuideTaillesRouteImport.update({
  id: '/aide/guide-tailles',
  path: '/aide/guide-tailles',
  getParentRoute: () => rootRouteImport,
} as any)
const AideContactRoute = AideContactRouteImport.update({
  id: '/aide/contact',
  path: '/aide/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AideConfidentialiteRoute = AideConfidentialiteRouteImport.update({
  id: '/aide/confidentialite',
  path: '/aide/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AideCguRoute = AideCguRouteImport.update({
  id: '/aide/cgu',
  path: '/aide/cgu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blouse-officielle': typeof BlouseOfficielleRoute
  '/college': typeof CollegeRoute
  '/commandes': typeof CommandesRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/niveau': typeof NiveauRoute
  '/panier': typeof PanierRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blouse-officielle': typeof BlouseOfficielleRoute
  '/college': typeof CollegeRoute
  '/commandes': typeof CommandesRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/niveau': typeof NiveauRoute
  '/panier': typeof PanierRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blouse-officielle': typeof BlouseOfficielleRoute
  '/college': typeof CollegeRoute
  '/commandes': typeof CommandesRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/niveau': typeof NiveauRoute
  '/panier': typeof PanierRoute
  '/aide/cgu': typeof AideCguRoute
  '/aide/confidentialite': typeof AideConfidentialiteRoute
  '/aide/contact': typeof AideContactRoute
  '/aide/guide-tailles': typeof AideGuideTaillesRoute
  '/aide/livraison': typeof AideLivraisonRoute
  '/aide/mentions-legales': typeof AideMentionsLegalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blouse-officielle'
    | '/college'
    | '/commandes'
    | '/enfants'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/niveau'
    | '/panier'
    | '/aide/cgu'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blouse-officielle'
    | '/college'
    | '/commandes'
    | '/enfants'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/niveau'
    | '/panier'
    | '/aide/cgu'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blouse-officielle'
    | '/college'
    | '/commandes'
    | '/enfants'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/niveau'
    | '/panier'
    | '/aide/cgu'
    | '/aide/confidentialite'
    | '/aide/contact'
    | '/aide/guide-tailles'
    | '/aide/livraison'
    | '/aide/mentions-legales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlouseOfficielleRoute: typeof BlouseOfficielleRoute
  CollegeRoute: typeof CollegeRoute
  CommandesRoute: typeof CommandesRoute
  EnfantsRoute: typeof EnfantsRoute
  LoginRoute: typeof LoginRoute
  LyceeRoute: typeof LyceeRoute
  MaternelleRoute: typeof MaternelleRoute
  NiveauRoute: typeof NiveauRoute
  PanierRoute: typeof PanierRoute
  AideCguRoute: typeof AideCguRoute
  AideConfidentialiteRoute: typeof AideConfidentialiteRoute
  AideContactRoute: typeof AideContactRoute
  AideGuideTaillesRoute: typeof AideGuideTaillesRoute
  AideLivraisonRoute: typeof AideLivraisonRoute
  AideMentionsLegalesRoute: typeof AideMentionsLegalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niveau': {
      id: '/niveau'
      path: '/niveau'
      fullPath: '/niveau'
      preLoaderRoute: typeof NiveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maternelle': {
      id: '/maternelle'
      path: '/maternelle'
      fullPath: '/maternelle'
      preLoaderRoute: typeof MaternelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lycee': {
      id: '/lycee'
      path: '/lycee'
      fullPath: '/lycee'
      preLoaderRoute: typeof LyceeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants': {
      id: '/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof EnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blouse-officielle': {
      id: '/blouse-officielle'
      path: '/blouse-officielle'
      fullPath: '/blouse-officielle'
      preLoaderRoute: typeof BlouseOfficielleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/mentions-legales': {
      id: '/aide/mentions-legales'
      path: '/aide/mentions-legales'
      fullPath: '/aide/mentions-legales'
      preLoaderRoute: typeof AideMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/livraison': {
      id: '/aide/livraison'
      path: '/aide/livraison'
      fullPath: '/aide/livraison'
      preLoaderRoute: typeof AideLivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/guide-tailles': {
      id: '/aide/guide-tailles'
      path: '/aide/guide-tailles'
      fullPath: '/aide/guide-tailles'
      preLoaderRoute: typeof AideGuideTaillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/contact': {
      id: '/aide/contact'
      path: '/aide/contact'
      fullPath: '/aide/contact'
      preLoaderRoute: typeof AideContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/confidentialite': {
      id: '/aide/confidentialite'
      path: '/aide/confidentialite'
      fullPath: '/aide/confidentialite'
      preLoaderRoute: typeof AideConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide/cgu': {
      id: '/aide/cgu'
      path: '/aide/cgu'
      fullPath: '/aide/cgu'
      preLoaderRoute: typeof AideCguRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlouseOfficielleRoute: BlouseOfficielleRoute,
  CollegeRoute: CollegeRoute,
  CommandesRoute: CommandesRoute,
  EnfantsRoute: EnfantsRoute,
  LoginRoute: LoginRoute,
  LyceeRoute: LyceeRoute,
  MaternelleRoute: MaternelleRoute,
  NiveauRoute: NiveauRoute,
  PanierRoute: PanierRoute,
  AideCguRoute: AideCguRoute,
  AideConfidentialiteRoute: AideConfidentialiteRoute,
  AideContactRoute: AideContactRoute,
  AideGuideTaillesRoute: AideGuideTaillesRoute,
  AideLivraisonRoute: AideLivraisonRoute,
  AideMentionsLegalesRoute: AideMentionsLegalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
