/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as NiveauRouteImport } from './routes/niveau'
import { Route as MaternelleRouteImport } from './routes/maternelle'
import { Route as LyceeRouteImport } from './routes/lycee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnfantsRouteImport } from './routes/enfants'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as IndexRouteImport } from './routes/index'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const NiveauRoute = NiveauRouteImport.update({
  id: '/niveau',
  path: '/niveau',
  getParentRoute: () => rootRouteImport,
} as any)
const MaternelleRoute = MaternelleRouteImport.update({
  id: '/maternelle',
  path: '/maternelle',
  getParentRoute: () => rootRouteImport,
} as any)
const LyceeRoute = LyceeRouteImport.update({
  id: '/lycee',
  path: '/lycee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantsRoute = EnfantsRouteImport.update({
  id: '/enfants',
  path: '/enfants',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/college': typeof CollegeRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/niveau': typeof NiveauRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/college': typeof CollegeRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/niveau': typeof NiveauRoute
  '/panier': typeof PanierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/college': typeof CollegeRoute
  '/enfants': typeof EnfantsRoute
  '/login': typeof LoginRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/niveau': typeof NiveauRoute
  '/panier': typeof PanierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/college'
    | '/enfants'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/niveau'
    | '/panier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/college'
    | '/enfants'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/niveau'
    | '/panier'
  id:
    | '__root__'
    | '/'
    | '/college'
    | '/enfants'
    | '/login'
    | '/lycee'
    | '/maternelle'
    | '/niveau'
    | '/panier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollegeRoute: typeof CollegeRoute
  EnfantsRoute: typeof EnfantsRoute
  LoginRoute: typeof LoginRoute
  LyceeRoute: typeof LyceeRoute
  MaternelleRoute: typeof MaternelleRoute
  NiveauRoute: typeof NiveauRoute
  PanierRoute: typeof PanierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/niveau': {
      id: '/niveau'
      path: '/niveau'
      fullPath: '/niveau'
      preLoaderRoute: typeof NiveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maternelle': {
      id: '/maternelle'
      path: '/maternelle'
      fullPath: '/maternelle'
      preLoaderRoute: typeof MaternelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lycee': {
      id: '/lycee'
      path: '/lycee'
      fullPath: '/lycee'
      preLoaderRoute: typeof LyceeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfants': {
      id: '/enfants'
      path: '/enfants'
      fullPath: '/enfants'
      preLoaderRoute: typeof EnfantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollegeRoute: CollegeRoute,
  EnfantsRoute: EnfantsRoute,
  LoginRoute: LoginRoute,
  LyceeRoute: LyceeRoute,
  MaternelleRoute: MaternelleRoute,
  NiveauRoute: NiveauRoute,
  PanierRoute: PanierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
